### PR TITLE
conflicts fixed

### PR DESCRIPTION
**Pull request by subhadeepchowdhury41**

### CODE REVIEW

**Review by yashraj-02-techie — CHANGES_REQUESTED** [review]
image

The anchor tags themselves are being displayed rather than the link.
This is fixed by using dangerouslysethtml prop. Or a better way is to use replace the anchor tags with Link tags from react and then export them and map them in the project.js file

**Comment by subhadeepchowdhury41** [comment]
bro slidedata mai change karo na wo. Maine toh iske bare mai kabse bol rha
hu

**Comment by yashraj-02-techie** [comment]
image
skit had different mentors for different projects. Now that we have separated the projects wouldn't it be correct to match the mentors to the respective projects?

**Comment by yashraj-02-techie** [comment]
image
The logo isn't centered at the bottom

**Comment by subhadeepchowdhury41** [comment]
meeching mai aa

**Pull request closed without merging**
